sudo: required
dist: trusty

services:
  - docker

language: node_js

before_script:
  - npm install -g gulp

script: gulp

node_js:
  - "stable"

after_success:
- docker build -t daves125125/sampleit-dashboard .
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push daves125125/sampleit-dashboard

notifications:
  email: false

